Fix typos in readme
google/dpy pull request #35
Opened 2018-04-30 16:23 UTC by jeis2497052

one more try to fix two typos if that is OK, also remove trailing white space.

2018-05-07 10:07 UTC, wesalvaro requested changes

2018-05-07 10:07 UTC, wesalvaro commented on README.md
> +Below are some simple examples for using dPy. For a complete usage example set that else runs, check out `example.py`.
"also"

2018-05-07 11:35 UTC, jeis2497052 commented on README.md
> +Below are some simple examples for using dPy. For a complete usage example set that else runs, check out `example.py`.
sorry, I can fix the word choice.

2018-05-09 13:48 UTC, jeis2497052 commented
broke my fork so closing for now.

2018-05-09 13:48 UTC, closed without merging